<?php
// $dir    = APP_PATH . '/controllers';
// // $files1 = scandir($dir);
// $files2 = scandir($dir, 1);

// // print_r($files1);
// echo "<pre>";
// print_r($files2);
// print_r(explode('Controller',$files2[0]));
// echo "</pre>";

?>

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <nav class="header">
        <div class="row">
       
            <div class="col-2">
                <?php echo $this->tag->linkTo('index/productList', 'Products List') ?>
            </div>
            <div class="col-2">
                <?php echo $this->tag->linkTo('index/addProduct', 'Product Add') ?>
            </div>
            <div class="col-2">
                <?php echo $this->tag->linkTo('index/orderList', 'Orders List') ?>
            </div>

            <div class="col-2">
                <?php echo $this->tag->linkTo('index/addOrder', 'Order Add') ?>

            </div>
            <div class="col-2">
                <?php echo $this->tag->linkTo('index/settings', 'Settings') ?>

            </div>
            <div class="col-2">
                <?php echo $this->tag->linkTo('acl', 'Acl') ?>

            </div>
        
        </div>
    </nav>
</body>

</html>