<?php
// echo "<pre>";
// $_POST['role'];
// print_r($allow);
// echo    "</pre>";
?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Order</title>
</head>

<body class='container text-center mt-5 border'>
    <h2 class='alert alert-success mt-4'>Allow Role</h2>
    </h2>
    <?php
    if (isset($msg)) {
        echo $msg;
    };
    ?>
    <?php echo $this->tag->form(['acl/data', 'class' => 'my-5']); ?>

    <p class="row">
        <label for="roles" class='label col-2 mx-5'>Roles</label>
        <?php

        $allroles = array();
        foreach ($roles as $role) {
            $allroles[$role->role] = $role->role;
        }

        echo $this->tag->select(['role', $allroles, 'class' => 'form-control col-6']) ?>
    </p>

    <p class="row">
        <label for="components" class='label col-2 mx-5'>Components</label>
        <?php
        $allcomponents = array();
        foreach ($components as $component) {
            $allcomponents[$component->component] = $component->component;
        }
        echo $this->tag->select(['component', $allcomponents, 'class' => 'form-control col-6 component']) ?>
    </p>
    <div id="actions-dropdown">
       
    </div>
    <p>
        <?php echo $this->tag->submitButton(["Allow", 'class' => 'btn  btn-primary mx-5']); ?>
    </p>
    <?php echo $this->tag->endForm(); ?>
</body>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="../../../../public/assests/js/script.js"></script>

</html>